# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Honeybits' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Honeybits

  target 'HoneybitsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HoneybitsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'XLPagerTabStrip', '~> 8.0'
pod 'Cosmos', '~> 15.0'
pod 'SwiftKeychainWrapper', '~> 3.0'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'GoogleSignIn'
pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'GoogleMaps'
pod 'SkyFloatingLabelTextField', '~> 3.0'
pod 'AwesomeEnum'
pod 'BFPaperButton'
pod 'FontAwesome.swift'
pod 'MaterialComponents/Cards'
pod 'IQKeyboardManagerSwift'
pod 'TagListView', '~> 1.0'
pod 'ImageSlideshow', '~> 1.6'
pod 'ImageSlideshow/Alamofire'

end
